apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-gateway
  namespace: lab4
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-checkout
  namespace: lab4
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-inventory
  namespace: lab4
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-pricing
  namespace: lab4

