apiVersion: v1
kind: Namespace
metadata:
  name: falco
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco
  namespace: falco
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: falco
  labels: { app: falco }
spec:
  selector:
    matchLabels: { app: falco }
  template:
    metadata:
      labels: { app: falco }
    spec:
      serviceAccountName: falco
      hostNetwork: true
      hostPID: true
      tolerations:
        - operator: Exists
      containers:
        - name: falco
          image: falcosecurity/falco:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args:
            - /usr/bin/falco
            - -K
            - /var/run/secrets/kubernetes.io/serviceaccount/token
            - -k
            - https://kubernetes.default
            - --node-name=$(NODE_NAME)
            - -o
            - json_output=true
          env:
            - name: NODE_NAME
              valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
          volumeMounts:
            - { name: dev-fs, mountPath: /host/dev }
            - { name: proc-fs, mountPath: /host/proc, readOnly: true }
            - { name: lib-modules, mountPath: /host/lib/modules, readOnly: true }
      volumes:
        - { name: dev-fs, hostPath: { path: /dev } }
        - { name: proc-fs, hostPath: { path: /proc } }
        - { name: lib-modules, hostPath: { path: /lib/modules } }
