server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
  }

  location = /api/arch {
    default_type application/json;
    add_header Cache-Control "no-store";
    return 200 '{"arch":"nanoservices-kubernetes","component":"nginx-configmap"}';
  }

  location = /api/ping {
    default_type application/json;
    add_header Cache-Control "no-store";
    return 200 '{"ok":true}';
  }

  location = /api/checkout {
    # INTENTIONAL MIGRATION BUG:
    # This upstream name worked in Docker Compose (service name),
    # but it is NOT the correct stable name in Kubernetes.
    proxy_pass http://checkout-svc/checkout;
    proxy_set_header X-Request-Id $http_x_request_id;
    #proxy_pass http://keda-add-ons-http-interceptor-proxy.keda:8080;
  }
}
